name: Fly Deploy

on:
  push:
    branches:
      - main
  pull_request:    
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-20.04
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy if push event
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
