name: Health Check

on:
  push:
    branches:
      - main

jobs:
  url_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        id: health_check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://pokedex-extra.fly.dev/
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false

      - name: Append results to file
        run: |
          echo "Date and Time: $(date)" >> health_check_results.txt
          if success(); then
            echo "Success pinging https://pokedex-extra.fly.dev/" >> health_check_results.txt
          else
            echo "Couldn't ping https://pokedex-extra.fly.dev/ >> health_check_results.txt
          fi
          echo "" >> health_check_results.txt
